//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** セットアップに使用する一時的なキーです。 */
public class SampleResponse: APIModel {

    public var sample: String?

    public init(sample: String? = nil) {
        self.sample = sample
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        sample = try container.decodeIfPresent("sample")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(sample, forKey: "sample")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? SampleResponse else { return false }
      guard self.sample == object.sample else { return false }
      return true
    }

    public static func == (lhs: SampleResponse, rhs: SampleResponse) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
